export const POPULATE_ITEM_LISTS = 'POPULATE_ITEM_LISTS'
export const MEMBERSHIP_ITEM_LISTS = 'MEMBERSHIP_ITEM_LISTS'
export const MEMBERCOUNT_ITEM_LISTS = 'MEMBERCOUNT_ITEM_LISTS'
export const MEMBERVISITCOUNT_ITEM_LISTS = 'MEMBERVISITCOUNT_ITEM_LISTS'
